version: "3.9"

services:
  db:
    image: postgres:16
    container_name: postgresdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: r_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d r_db"]
      interval: 5s
      timeout: 5s
      retries: 20
  mongodb:
    image: mongo:7
    container_name: documentdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  pgdata_db:
  mongodata:
