"""Initial migration

Revision ID: 8daa4e4f0409
Revises: 
Create Date: 2026-04-18 17:37:27.277171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8daa4e4f0409'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User_creadintials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_users_email'),
    sa.UniqueConstraint('username', name='uq_users_username')
    )
    op.create_index(op.f('ix_User_creadintials_email'), 'User_creadintials', ['email'], unique=True)
    op.create_index(op.f('ix_User_creadintials_id'), 'User_creadintials', ['id'], unique=False)
    op.create_index(op.f('ix_User_creadintials_username'), 'User_creadintials', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_User_creadintials_username'), table_name='User_creadintials')
    op.drop_index(op.f('ix_User_creadintials_id'), table_name='User_creadintials')
    op.drop_index(op.f('ix_User_creadintials_email'), table_name='User_creadintials')
    op.drop_table('User_creadintials')
    # ### end Alembic commands ###
